#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : libiptcdata
Version  : 1.0.5
Release  : 1
URL      : https://github.com/ianw/libiptcdata/releases/download/release_1_0_5/libiptcdata-1.0.5.tar.gz
Source0  : https://github.com/ianw/libiptcdata/releases/download/release_1_0_5/libiptcdata-1.0.5.tar.gz
Summary  : IPTC tag library
Group    : Development/Tools
License  : LGPL-2.0 LGPL-2.1+
Requires: libiptcdata-bin = %{version}-%{release}
Requires: libiptcdata-lib = %{version}-%{release}
Requires: libiptcdata-license = %{version}-%{release}
Requires: libiptcdata-locales = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : docbook-xml
BuildRequires : gettext
BuildRequires : gtk-doc
BuildRequires : gtk-doc-dev
BuildRequires : libxslt-bin
BuildRequires : perl(XML::Parser)

%description
libiptcdata is a library for parsing, editing, and saving IPTC data
stored inside images.  IPTC is a standard for encoding metadata such
as captions, titles, locations, etc. in the headers of an image file.
libiptcdata also includes a command-line utility for modifying the
metadata.

%package bin
Summary: bin components for the libiptcdata package.
Group: Binaries
Requires: libiptcdata-license = %{version}-%{release}

%description bin
bin components for the libiptcdata package.


%package dev
Summary: dev components for the libiptcdata package.
Group: Development
Requires: libiptcdata-lib = %{version}-%{release}
Requires: libiptcdata-bin = %{version}-%{release}
Provides: libiptcdata-devel = %{version}-%{release}
Requires: libiptcdata = %{version}-%{release}

%description dev
dev components for the libiptcdata package.


%package doc
Summary: doc components for the libiptcdata package.
Group: Documentation

%description doc
doc components for the libiptcdata package.


%package lib
Summary: lib components for the libiptcdata package.
Group: Libraries
Requires: libiptcdata-license = %{version}-%{release}

%description lib
lib components for the libiptcdata package.


%package license
Summary: license components for the libiptcdata package.
Group: Default

%description license
license components for the libiptcdata package.


%package locales
Summary: locales components for the libiptcdata package.
Group: Default

%description locales
locales components for the libiptcdata package.


%prep
%setup -q -n libiptcdata-1.0.5

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1565204280
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1565204280
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/libiptcdata
cp COPYING %{buildroot}/usr/share/package-licenses/libiptcdata/COPYING
%make_install
%find_lang iptc
%find_lang libiptcdata

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/iptc

%files dev
%defattr(-,root,root,-)
/usr/include/libiptcdata/_stdint.h
/usr/include/libiptcdata/iptc-data.h
/usr/include/libiptcdata/iptc-dataset.h
/usr/include/libiptcdata/iptc-jpeg.h
/usr/include/libiptcdata/iptc-log.h
/usr/include/libiptcdata/iptc-mem.h
/usr/include/libiptcdata/iptc-tag.h
/usr/include/libiptcdata/iptc-utils.h
/usr/lib64/libiptcdata.so
/usr/lib64/pkgconfig/libiptcdata.pc

%files doc
%defattr(0644,root,root,0755)
/usr/share/gtk-doc/html/libiptcdata/ch01.html
/usr/share/gtk-doc/html/libiptcdata/ch02.html
/usr/share/gtk-doc/html/libiptcdata/ch03.html
/usr/share/gtk-doc/html/libiptcdata/home.png
/usr/share/gtk-doc/html/libiptcdata/index.html
/usr/share/gtk-doc/html/libiptcdata/iptc-about.html
/usr/share/gtk-doc/html/libiptcdata/iptc-commandline.html
/usr/share/gtk-doc/html/libiptcdata/iptc-i18n.html
/usr/share/gtk-doc/html/libiptcdata/iptc-libjpeg.html
/usr/share/gtk-doc/html/libiptcdata/iptc-overview.html
/usr/share/gtk-doc/html/libiptcdata/left-insensitive.png
/usr/share/gtk-doc/html/libiptcdata/left.png
/usr/share/gtk-doc/html/libiptcdata/libiptcdata-data.html
/usr/share/gtk-doc/html/libiptcdata/libiptcdata-dataset.html
/usr/share/gtk-doc/html/libiptcdata/libiptcdata-jpeg.html
/usr/share/gtk-doc/html/libiptcdata/libiptcdata-log.html
/usr/share/gtk-doc/html/libiptcdata/libiptcdata-mem.html
/usr/share/gtk-doc/html/libiptcdata/libiptcdata-tag.html
/usr/share/gtk-doc/html/libiptcdata/libiptcdata-utils.html
/usr/share/gtk-doc/html/libiptcdata/libiptcdata.devhelp2
/usr/share/gtk-doc/html/libiptcdata/right-insensitive.png
/usr/share/gtk-doc/html/libiptcdata/right.png
/usr/share/gtk-doc/html/libiptcdata/style.css
/usr/share/gtk-doc/html/libiptcdata/up-insensitive.png
/usr/share/gtk-doc/html/libiptcdata/up.png

%files lib
%defattr(-,root,root,-)
/usr/lib64/libiptcdata.so.0
/usr/lib64/libiptcdata.so.0.3.3

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/libiptcdata/COPYING

%files locales -f iptc.lang -f libiptcdata.lang
%defattr(-,root,root,-)

